### ISSUE TITLE
商品詳細のデザイン

### ISSUE THREAD

**Issue by rotsuya** [darumaya/old#126]
- [x] 画像を回転する。

**Comment by rotsuya** [comment]
画像の回転は、「可逆（または無劣化） 回転 JPEG Mac」でフリーソフトを探す。

**Comment by rotsuya** [comment]
あるべき姿を考えた。

「きもののお手入れ」の事例が「きものの再生事例」。
同様に「着こなしのご提案」の事例が「着こなしのご提案の事例」。
メニューに「着こなしのご提案の事例」を追加し、7つにするのがよい。
今回のリニューアルでは見送る。

**Comment by rotsuya** [comment]
今回は、1商品ごとに、正方形の画像を3個並べる。
クリックすると、lightboxでギャラリーを表示する。

**Comment by yakken** [comment]
画像の回転はPhoenix Slidesというソフトを使いました。

**Comment by rotsuya** [comment]
画像を正方形にするのは、 #181 に分割する
