### ISSUE TITLE
スマホで見ると、下層ページボタン内の文章2行目がはみ出している

### ISSUE THREAD

**Issue by yakken** [darumaya/old#150]
![dlab1_ _](https://cloud.githubusercontent.com/assets/7663199/5520435/9aacadf4-89c4-11e4-9bf7-c71745c920d5.jpg)

**Comment by rotsuya** [comment]
こ、これは難しい。

1行と2行のどちらかに最適化するのではなく、間を取るしかないかなぁ。
1行だとなんか下の余白が広く感じる、2行だと狭く感じる、って感じの。
priority-3 で対応します。
