### ISSUE TITLE
本番環境で表示されない画像がある

### ISSUE THREAD

**Issue by yakken** [darumaya/old#157]
トップ
- [x] 催事のご案内

お店のご案内
- [x] カルーセル内の平塚駅北口

メディア掲載履歴
- [x] 謎解き江戸のススメ

洗い張り
- [x] カルーセル内の端縫い

仕立て
- [x] 関連のあるページのきものを仕立て直す
- [x] 関連のあるページのきものを染め直してコートに仕立て

染め
- [x] カルーセル内の事前確認
- [x] 関連のあるページのきものを染め直した事例紹介
- [x] 関連のあるページのきものを染め直してコートに仕立て

引き振袖に仕立て直す
- [x] お手入れ前

無地
- [x] カルーセル内の紋を決める

男のきもの
- [x] 関連のあるページのゆかた・夏物

**Comment by rotsuya** [comment]
priority-1 で確認します。

**Comment by rotsuya** [comment]
ん？ Assignee @yakken でいいの？

**Comment by yakken** [comment]
自力で何とかしてみようと試みたのですが、無理そうでした。。
GitHubのBranchesをmasterにしてSyncしようとすると、エラーが出ます。
（本issueとは別問題かもしれませんが。）

**Comment by rotsuya** [comment]
https://github.com/darumaya/darumaya.github.io/tree/master/images
に "Sorry, we had to truncate this directory to 1,000 files. 1,349 entries were omitted from the list." と表示されている。ファイル数が多すぎるのが原因かも。フォルダを分ければ解決すると思います。

`images/`を先頭文字で`images-a-e/` `images-f-j/` `images-k-o/` `images-p-t/` `images-u-z/`のように5分割するというのはどうでしょう？他に良い分け方を思いつきます？

よければ、これで対応します。

**Comment by yakken** [comment]
OKです。ご対応お願いします！

**Comment by rotsuya** [comment]
```
images/
```

のファイルを

```
images/a/
images/c/
images/d/
images/f/
images/h/
images/k/
images/l/
images/m/
images/n/
images/o/
images/r/
images/s/
images/t/
images/y/
```

に分けたが、まだ画像が表示されるようにならない。

他の方法を考える。

**Comment by rotsuya** [comment]
https://help.github.com/articles/what-is-my-disk-quota/
に、容量をなるべく1GB以下に抑えてねと書いてある。

``` sh
$ du -m -s darumaya.github.io/
3593    darumaya.github.io/
```

全体で3593÷1024＝3.5GB使っている！
これが原因かもしれない。

``` sh
$ du -m -s darumaya.github.io/images/
232 darumaya.github.io/images/
```

imagesの中の画像は0.2GBに収まっている。

``` sh
$ du -m -s darumaya.github.io/.git/
1759    darumaya.github.io/.git/
```

過去の履歴で1.7GBも使っている。

``` sh
$ du -m -s darumaya.github.io/src/images/
1268    darumaya.github.io/src/images/
```

オリジナル画像で1.2GBも使っている。

画像のlgサイズやmdサイズはめったに使わない。画像サイズを見直す。

過去の履歴は、
https://help.github.com/articles/remove-sensitive-data/
を参照しながら削除してみる。

オリジナル画像は、八木くんのローカルだけに置くようにする。

**Comment by rotsuya** [comment]
http://image1.darumaya-gofuku.jp/ 、 http://image2.darumaya-gofuku.jp/ 、 http://image3.darumaya-gofuku.jp/ のへの移行を進めているところでしたが、1GBオーバーとは別の原因であることがわかりました。
- 画像の拡張子が .jpg なのにHTMLで .JPG を指定している
- 画像の拡張子が .JPG なのにHTMLで .jpg を指定している

のどちらかが原因でした。別ドメインへの移行は中止し、拡張子を修正して、動作を確認します。

**Comment by rotsuya** [comment]
結局、拡張子を訂正したらなおりました。クローズします。
