### ISSUE TITLE
商品詳細の画像のレイアウトを工夫する

### ISSUE THREAD

**Issue by rotsuya** [darumaya/old#181]

**Comment by rotsuya** [comment]
正方形にトリミングするのではなく、「縦長、横長、横長」のデザインを工夫する。

**Comment by rotsuya** [comment]
## 2015/01/08 打ち合わせ
- 横幅が広い時はテキストは右側に。
- 横幅が狭い時はテキストを下側に。
- 見た目をかっこ良くするのは後回し。 #234 に移動した。ほどほどで一度リリースする。

**Comment by rotsuya** [comment]
@yakken
今月のおすすめと附下・訪問着のレイアウトを更新し、devブランチにマージしたので、時間があればローカル環境で確認をお願いします。

**Comment by yakken** [comment]
今月のおすすめ、附下・訪問着、小紋、紬、振袖・留袖、ゆかた・夏物、男のきもの、のデザイン変更をリリースしました。
