### ISSUE TITLE
1階層ページのサムネイルの並びがずれる

### ISSUE THREAD

**Issue by rotsuya** [darumaya/old#213]
Jumbotron用の画像のサイズが揃っていないため、1階層ページのサムネイルの並びがずれてしまう。Jumbotron用の画像のサイズを揃えられないか。

http://www.darumaya-gofuku.jp/information/

/src/images/s/staff-jumbotron-DSC05054.jpg
5914 × 2400 (4.928… : 2)
↓
http://www.darumaya-gofuku.jp/images/s/staff-jumbotron-DSC05054-xs-2x.jpg
1535 × 623
http://www.darumaya-gofuku.jp/images/s/staff-jumbotron-DSC05054-xs.jpg
768 × 312

/src/images/h/history-jumbotron-P1070135.jpg
1108 × 443 (5.002… : 2)
↓
http://www.darumaya-gofuku.jp/images/h/history-jumbotron-P1070135-xs-2x.jpg
1536 × 614
http://www.darumaya-gofuku.jp/images/h/history-jumbotron-P1070135-xs-2x.jpg
768 × 307

**Comment by yakken** [comment]
対応しました。
他にもたくさんありました・・。。

働いている人
歴史
メディア掲載履歴
お客様の声
洗い張り
紬
お客様感謝祭
洗い張り体験
