### ISSUE TITLE
Google+に対応して検索結果に顔を出す

### ISSUE THREAD

**Issue by yakken** [darumaya/old#230]
インセプションデッキより。

**Comment by yakken** [comment]
米Googleは6月25日（現地時間）、検索結果で著者情報を表示する「Authorship Program」でのプロフィール写真の表示を終了すると発表した。

http://www.itmedia.co.jp/news/articles/1406/27/news053.html

といういことで、プロフィール写真の表示終わってました。。笑

**Comment by rotsuya** [comment]
そうでしたか…。
