### ISSUE TITLE
GoogleAdWordsとYahoo!プロモーション広告のコンバージョントラッキングコードの埋め込み

### ISSUE THREAD

**Issue by yakken** [darumaya/old#238]
どのページヘの到達をコンバージョンとするかを検討する。
現在：お問い合わせ
　　　お店のご紹介

今後：お問い合わせ
　　　ニュースレター

・・他に無いか考える
- [ ] お問い合せページ
  http://www.darumaya-gofuku.jp/information/contact.html

GoogleAdWords

<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1041073051;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "dwxACKqZ2FgQm4e28AM";
var google_remarketing_only = false;
/* ]]> */
</script>

<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>

<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1041073051/?label=dwxACKqZ2FgQm4e28AM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

Yahoo!プロモーション広告

<script type="text/javascript">
/* <![CDATA[ */
var yahoo_conversion_id = 1000172892;
var yahoo_conversion_label = "T4oFCL6V2FgQ08rwygM";
var yahoo_conversion_value = 500;
/* ]]> */
</script>

<script type="text/javascript" src="http://i.yimg.jp/images/listing/tool/cv/conversion.js">
</script>

<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://b91.yahoo.co.jp/pagead/conversion/1000172892/?value=500&amp;label=T4oFCL6V2FgQ08rwygM&amp;guid=ON&amp;script=0&amp;disvt=true"/>
</div>
</noscript>

- [ ] ニュースレター
  http://www.darumaya-gofuku.jp/information/newsletter.html

GoogleAdWords

<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1041073051;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "HKgHCIi81lgQm4e28AM";
var google_remarketing_only = false;
/* ]]> */
</script>

<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>

<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1041073051/?label=HKgHCIi81lgQm4e28AM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

Yahoo!プロモーション

<script type="text/javascript">
/* <![CDATA[ */
var yahoo_conversion_id = 1000172892;
var yahoo_conversion_label = "bUfNCIW81lgQ08rwygM";
var yahoo_conversion_value = 250;
/* ]]> */
</script>

<script type="text/javascript" src="http://i.yimg.jp/images/listing/tool/cv/conversion.js">
</script>

<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://b91.yahoo.co.jp/pagead/conversion/1000172892/?value=250&amp;label=bUfNCIW81lgQ08rwygM&amp;guid=ON&amp;script=0&amp;disvt=true"/>
</div>
</noscript>

**Comment by yakken** [comment]
フォームの送信ボタンを押された時にコンバージョンしたとするのが良い。

コンバージョン設定用コードを取得する際に、ページURLを入力する必要があるのですが、フッターのフォームの場合URLはどう設定すれば良いですか？

**Comment by rotsuya** [comment]
Google AdWords、Yahoo!プロモーション広告のコンバージョンについて調べてみましたが、静的なWebページにしか設定できず、ボタンのクリックでコンバージョンにすることはできないみたいです。

Google AdWordsに関しては、Google Analyticsと連携させ、Google Analyticsの目標を使うとできるます。以下に説明があります。
https://support.google.com/adwords/answer/2375435

一度、喜ばせちゃった後で、がっかりさせるみたいで申し訳ないです。

**Comment by rotsuya** [comment]
Yahooは諦める。できないものは仕方ない。Google Analyticsと同傾向と考える。

Google AdWordsはGoogle Analyticsのアクションを使う。

| Category = フォームの種類 | Action = ページ名 | Label = URL |
| :-- | :-- | :-- |
| お問い合わせ | フッター | URL |
|  | お問い合わせ | (URL) |
| メルマガ | フッター | URL |
|  | ニュースレター※ | (URL) |
|  | 催事のご案内※ | (URL) |
| ポストカード | ニュースレター | (URL) |
|  | 催事のご案内 | (URL) |
| お客さまの声 | お客さまの声 | (URL) |

※ MailChimp

**Comment by rotsuya** [comment]
最優先で進める。

**Comment by rotsuya** [comment]
催事のご案内ページにも、メルマガ(MailChimp)フォームがあるが、上のリストから漏れていたので追加した。

**Comment by rotsuya** [comment]
とりあえずlocalブランチに仕込んで、Mac Safariで各フォームを1回ずつ送信してみた。明日、GAで結果を確認する。

OKなら、Mac Chrome、Win IE、Mac Firefox、iOS Safariでも動作確認。

また翌日、GAで確認し、OKなら、デバッグモードをオフにして、公開する。

**Comment by rotsuya** [comment]
うーん、記録されていないなぁ。見なおしてみます。
https://www.google.com/analytics/web/?hl=ja&pli=1#report/content-event-overview/a1119315w10411150p10876268/%3F_u.date00%3D20150305%26_u.date01%3D20150305%26overview-dimensionSummary.selectedGroup%3Dvisitors%26overview-dimensionSummary.selectedDimension%3Danalytics.eventLabel/

**Comment by rotsuya** [comment]
プログラムは間違っていなさそう。 http://localhost:4000 でテストしてるから、Google Analyticsに記録されないだけかも。

方針を変更し、副作用(デグレード)が無いことをテストした上で、本番にデプロイしてから、Google Analyticsを確認する。

**Comment by rotsuya** [comment]
#### localhost:4000 でフォームが送信されるか(デグレードがないか)、コンソールログが出力されるか、のテスト
- Mac / Safari
  - [x] フッター / お問い合わせ
  - [x] フッター / メルマガ
  - [x] ニュースレター / ポストカード
  - [x] ニュースレター / メルマガ
  - [x] お客さまの声 / お客さまの声
  - [x] お問い合わせ / お問い合わせ
  - [x] 催事のご案内 / ポストカード
  - [x] 催事のご案内 / メルマガ
- Mac / Chrome
  - [x] フッター / お問い合わせ
  - [x] フッター / メルマガ
  - [x] ニュースレター / ポストカード
  - [x] ニュースレター / メルマガ
  - [x] お客さまの声 / お客さまの声
  - [x] お問い合わせ / お問い合わせ
  - [x] 催事のご案内 / ポストカード
  - [x] 催事のご案内 / メルマガ
- Mac / Firefox
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- iPhone / Safari
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- Windows / IE9
  - [x] フッター / お問い合わせ
  - [x] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [x] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [x] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ

**Comment by rotsuya** [comment]
全てはテストしていないが、大丈夫そうなので、リリースしてみる。

**Comment by rotsuya** [comment]
リリースしたので、テストする。

#### www.darumaya-gofuku.jp でフォームが送信されるか(デグレードがないか)のテスト
- Mac / Safari
  - [x] フッター / お問い合わせ
  - [x] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- Mac / Chrome
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [x] ニュースレター / ポストカード
  - [x] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- Mac / Firefox
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [x] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- iPhone / Safari
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [x] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- Windows / IE9
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [x] 催事のご案内 / ポストカード
  - [x] 催事のご案内 / メルマガ

**Comment by rotsuya** [comment]
#### Google Analyticsでイベントが記録されているかのテスト

- Mac / Safari
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- Mac / Chrome
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- Mac / Safari
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- iPhone / Firefox
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ
- Windows / IE9
  - [ ] フッター / お問い合わせ
  - [ ] フッター / メルマガ
  - [ ] ニュースレター / ポストカード
  - [ ] ニュースレター / メルマガ
  - [ ] お客さまの声 / お客さまの声
  - [ ] お問い合わせ / お問い合わせ
  - [ ] 催事のご案内 / ポストカード
  - [ ] 催事のご案内 / メルマガ

**Comment by rotsuya** [comment]
#### Google Analyticsでイベントが記録されているかのテスト

| Category | Action | ブラウザ | クリック数 | GAのカウント数 |
| :-- | :-- | :-- | --: | --: |
| お問い合わせ | フッター | Mac / Safari | 1 | 0 |
|  | お問い合わせ | iPhone / Safari | 1 | 1 |
| メルマガ | フッター | Mac / Safari | 1 | 0 |
|  | ニュースレター | Mac / Chrome | 1 | 1 |
|  | 催事のご案内 | Win / IE9 | 1 | 1 |
| ポストカード | ニュースレター | Mac / Chrome | 1 | 1 |
|  | 催事のご案内 | Win / IE9 | 1 | 2 |
| お客さまの声 | お客さまの声 | Mac / Firefox | 1 | 0 |

**Comment by rotsuya** [comment]
数がずれてしまった。電車の中で、電波状態が悪かったのかもしれない。もう一度テストする。

**Comment by rotsuya** [comment]
#### Google Analyticsでイベントが記録されているかのテスト

| Category | Action | ブラウザ | クリック数 | GAのカウント数 |
| :-- | :-- | :-- | --: | --: |
| お問い合わせ | フッター | Mac / Safari | 1 | 0 |
|  | お問い合わせ | iPhone / Safari | 1 | 1 |
| メルマガ | フッター | Mac / Safari | 1 | 0 |
|  | ニュースレター | Mac / Chrome | 1 | 1 |
|  | 催事のご案内 | Win / IE9 | 1 | 1 |
| ポストカード | ニュースレター | Mac / Chrome | 1 | 1 |
|  | 催事のご案内 | Win / IE9 | 1 | 1 |
| お客さまの声 | お客さまの声 | Mac / Firefox | 1 | 1 |

フッターがダメなのか、Mac Safariがダメなのか？

**Comment by rotsuya** [comment]
Chromeでフッターのテストをしてみる。

| Category | Action | ブラウザ | クリック数 | GAのカウント数 |
| :-- | :-- | :-- | --: | --: |
| お問い合わせ | フッター | Mac / Chrome | 1 | 1 |
| メルマガ | フッター | Mac / Chrome | 1 | 1 |

フッターのバグではなく、Mac Safariの問題のようだ。

**Comment by rotsuya** [comment]
SafariにGoogle アナリティクス オプトアウト アドオンをインストールしているのが原因かも！

**Comment by rotsuya** [comment]
| Category | Action | ブラウザ | クリック数 | GAのカウント数 |
| :-- | :-- | :-- | --: | --: |
| お問い合わせ | フッター | Mac / Safari | 1 | 1 |
| メルマガ | フッター | Mac / Safari | 1 | 1 |

カウントされた。これにてリリース完了。
