### ISSUE TITLE
静的ファイル用のDNS設定

### ISSUE THREAD

**Issue by rotsuya** [darumaya/old#283]
ブログの静的ファイル(CSSやJavaScript)を、GitHubを使って http://static.darumaya-gofuku.jp/ で公開したい。DNS設定が必要。

**Comment by rotsuya** [comment]
@yakken バリュードメインに以下のDNS設定を追加してください。よろしくお願いします。

``` dns
cname static darumaya.github.io.
```

**Comment by yakken** [comment]
設定しました。
