### ISSUE TITLE
問い合わせフォームのメール送信スクリプト

### ISSUE THREAD

**Issue by rotsuya** [darumaya/old#29]

**Comment by rotsuya** [comment]
八木くんに飛ばすのは、Googleスプレッドシートの機能でもできるが、お客さんにもメールを飛ばしたいので、必要。

**Comment by yakken** [comment]
お客様の声、メールマガジン登録、問い合わせ、すべてについてお客様へメールを飛ばしたい

**Comment by rotsuya** [comment]
@yakken お客さまの声ではメールアドレスを取得していないので、メールを送信できない。

**Comment by rotsuya** [comment]
メール送信スクリプトのテストが終わったが、メールのFromを変更できないことがわかった。スクリプトを設置した人のGoogleアカウントのメールアドレスが使用される。 contact@darumaya-gofuku.jp でスクリプトを設置する必要がある。

**Comment by rotsuya** [comment]
手順は以下のとおり。
1. Googleスプレッドシートを開く。
2. 「ツール」→「スクリプトエディタ」→「スクリプトを作成」→「空のプロジェクト」を選択する。
3. スクリプトを削除し、sendMail.jsのコードを貼り付ける。5行目(Subject)、6~7行目(本文)を適宜書き換える。Fromのアドレスとは別のアドレスに返信してもらいたい場合は、8行目(`replyTo`)にアドレスを書く。Cc、Bccを設定したい場合は、9行目(`ccs`)、10行目(`bccs`)に配列の書式でアドレスを書く。
4. 「ファイル」→「保存」をクリックする。プロジェクト名は何でもいいが、`sendMail`などとする。
5. 「リソース」→「現在のプロジェクトのトリガー」をクリックする。
6. 「トリガーが設定されていません。今すぐ追加するにはここをクリックしてください。」
7. 実行: `sendMail`、イベント: `スプレッドシートから`、`フォーム送信時`を選択する。

### sendMail.js

``` js
function sendMail() {
  Logger.log('sendMail() start');

  // 設定
  var subject = 'お問い合わせを受け付けました';
  var header = 'お問い合わせを受け付けました。\n\n'
  var footer = '\n\nだるまや京染本店 <contact@darumaya-gofuku.jp>';
  var replyTo = '';
  var ccs = [];
  var bccs = [];

  try {
    var body = header;

    // スプレッドシートの操作
    var sheet   = SpreadsheetApp.getActiveSheet();
    var colLength = sheet.getLastColumn();
    var rowLengh = sheet.getLastRow();
    var range   = sheet.getDataRange();

    // メール件名・本文作成と送信先メールアドレス取得
    for (var i = 1; i <= colLength; i++) {
      var colName  = range.getCell(1, i).getValue();    // カラム名
      var colValue = range.getCell(rowLengh, i).getValue(); // 入力値
      body += colName + ':\n' + colValue + '\n\n';
      if (colName.search(/^メールアドレス/) !== -1) {
        var to = colValue;
      }
    }

    body += footer;

    var message = {};
    if (bccs.length > 0) {
      message.bcc = bccs.join(',');
    }
    message.body = body || '';
    if (ccs.length > 0) {
      message.cc = ccs.join(',');
    }
    if (replyTo) {
      message.replyTo = replyTo;
    }
    if (subject) {
      message.subject = subject;
    }
    if (to) {
      message.to = to;
    } else {
      throw 'toが存在しない';
    }
    // メール送信
    MailApp.sendEmail(message);

  } catch(e) {
    MailApp.sendEmail('contact@darumaya-gofuku.jp', 'メール送信エラー', e.message);
  }
}
```

**Comment by yakken** [comment]
バラバラだったGoogleフォームを統一させました。

サイトマップにGoogleフォーム一覧用シートを追記しました
https://drive.google.com/#folders/0B5nycPC2rcflNUY3aUktbHhSeG8

contact@darumaya-gofuku.jpでスプレッドシートからスクリプトエディタを設定しました。
が、送信されたりされなかったりします。
再度テストしてみます。

**Comment by yakken** [comment]
設定完了しました。
