### ISSUE TITLE
Front MatterのJumbtron画像のパスに{width}{pixel_ratio}がない

### ISSUE THREAD

**Issue by rotsuya** [darumaya/old#56]
表記を統一したい。

**Comment by yakken** [comment]
対応します。

洗い張りページで言うと、
/images/araihari-jumbotron-R1046195.jpg
を
/images/araihari-jumbotron-R1046195-{width}{pixel_ratio}.jpg
に変更すればよいでしょうか？

洗い張りページのみ書き換えてみたところ、画像が表示されなくなってしまいました。

**Comment by rotsuya** [comment]
まだ対応しなくて大丈夫です。今、変更すると表示されなくなります。これは自分用のタスクで、備忘のために登録しています。見た目の部分の作業が終わったら、このような見た目に関係ないタスクに対応する予定です。

**Comment by yakken** [comment]
了解です。

**Comment by rotsuya** [comment]
#56 で対応完了。
